### ISSUE TITLE
cmp_read_sinteger() doesn't match naming convention

### ISSUE THREAD

**Issue by csstup** [camgunz/cmp#16]
cmp_read_sinteger() doesn't appear to match the naming standard the other functions do.   Shouldn't it be cmp_read_sint()?

**Comment by camgunz** [comment]
I think what you're getting at is the inconsistency between the read/write functions (`cmp_read_sinteger` and `cmp_write_sint`).  I can't change it to `cmp_read_sint`, because then `cmp_read_uinteger` also becomes `cmp_read_uint`, and that's already used.  The "fix" is really to change `cmp_write_sint` to `cmp_write_sinteger`.  I'll probably make that change at some point.  I don't make any guarantees about compatibility between versions, so a breaking change like this is no problem.  I'll probably make it in its own version though, just to avoid being spiteful, haha.

Thanks for bringing this up!

**Comment by csstup** [comment]
Perhaps just a #define macro for backwards compatibility.   Just stating they weren't symmetrical and it reads better when they are.

Thanks!

**Comment by camgunz** [comment]
Done in 3c0b30c!
