### ISSUE TITLE
Use cmp with char buffer instead of file

### ISSUE THREAD

**Issue by timlehr** [camgunz/cmp#21]
Hi,

I'm new to MsgPack and C, but I'm loving your implementation so far. I already have some great results. I'm using it to unpack / pack data from a network socket, which stores it into an unsigned char buffer. I couldn't get cmp to read / write directly on the char buffer instead of a file (your example). Is there a simple way to do that and if yes, could you provide me with a simple example how to do it? Thanks a lot in advance!

**Comment by antoinealb** [comment]
You can use this library, which precisely does this: https://github.com/Stapelzeiger/cmp_mem_access

**Comment by timlehr** [comment]
Awesome, I'll check it out. Thanks for the super fast reply! :)

**Comment by camgunz** [comment]
Yeah @antoinealb's library is the most straightforward way to do that; it generally boils down to a buffer, a size, a cursor, and callbacks that use them.  Since this case is probably more common than the file case, I might add some docs or just call out Antoine's library, or both.

**Comment by camgunz** [comment]
Yeah @antoinealb's library is the most straightforward way to do that; it generally boils down to a buffer, a size, a cursor, and callbacks that use them.  Since this case is probably more common than the file case, I might add some docs or just call out Antoine's library, or both.

And thanks for the kind words :)

**Comment by antoinealb** [comment]
Maybe you can include it in cmp if @Stapelzeiger is ok.

**Comment by camgunz** [comment]
Sure yeah, I'll look into it; maybe it's worth adding like a contrib folder or something, if authors are amenable.

**Comment by antoinealb** [comment]
Or create a cmp organization and add contribution as other repositories, I don't know.

**Comment by slact** [comment]
I'll chime in here, since it took me a few hours of head scratching to figure it out. I use cmp to read messages from redis from within nginx:  https://github.com/slact/nchan/blob/master/src/store/redis/store.c , just search around for `cmp_ctx_t`. 

Like @camgunz says, you'll want some kind of buffer and a cursor. Use cmp to parse metadata and small fixed-length values (like numbers), and if you encounter a string read from your buffer directly using the length given by cmp.

@camgunz: *cmp is so much nicer than the default msgpack c lib. thanks for making it!

**Comment by camgunz** [comment]
Thanks for the compliment @slact.  I wrote CMP because I wanted more low-level control over my buffers and allocations, but I think MsgPack's included C implementation is probably more convenient if you don't want to worry about that.  Actually this issue is a good example of that.

When I get some free time I'll investigate the organization thing; curating a list of stuff built on top of CMP seems like a cool idea, but I don't know how much effort it's really worth.  There are examples of other projects doing this kind of thing though.  [Hiredis](https://github.com/redis/hiredis/tree/master/adapters) has a list of adapters for various event libraries, for one, which has been specifically helpful to me.  It's something to think about anyway.

**Comment by timlehr** [comment]
cmp_mem_access works great! Thank you guys!
